### ISSUE TITLE
Calibrar sensor de temperatura y humedad

### ISSUE THREAD

**Issue by violenti** [rlyehlab/ETER#24]

**Comment by violenti** [comment]
Hola @nanocastro , queria saber si tenes documetanción del procedimiento para calibrar los sensores. Con el de tem y humedad, tenemos pensado usar un higrómetro, pero con el aíre no sabes que parámetro a utilizar.

**Comment by nanocastro** [comment]
buenas
para calibrar los sensores de partículas hay dos opciones. una es en el lab que para partículas no es tan sencillo (pueden ver [aca](https://github.com/rutian/MyPart) una test chamber y un generador de particulas) y la otra es co-localizar los sensores junto a un equipo que sirva de referencia, digamos otro equipo calibrado. 
algunos link
lab https://www.tandfonline.com/doi/pdf/10.1080/02786826.2015.1100710
       https://www.ri.cmu.edu/pub_files/2016/12/m_taylor_robotics_2016.pdf
field https://core.ac.uk/download/pdf/25709801.pdf
y aca hay evaluaciones de muchos sensores
http://www.aqmd.gov/aq-spec/evaluations

**Comment by thessaly** [comment]
This issue was moved to rlyehlab/eter-monitor#3
