### ISSUE TITLE
Trabajar sobre objetivos del juego

### ISSUE THREAD

**Issue by thessaly** [rlyehlab/eter#27]
Yelomba nos va a mandar unas preguntas guía para pensar el juego antes del miércoles - Las pongo acá apenas las tenga

**Comment by thessaly** [comment]
https://juegosdelcomun.arsgames.net/
https://arsgames.net

**Comment by thessaly** [comment]
Cerrado con @yelomba y @Marshmaline

**Comment by yelomba** [comment]
http://twinery.org/ interesante para plantear desde aqui el juego. y es open
