### ISSUE TITLE
Materiales para difusión

### ISSUE THREAD

**Issue by thessaly** [rlyehlab/ETER#3]
Lo inicio yo @thessaly y lo distribuyo vía pad

**Comment by thessaly** [comment]
Armé este pad: https://pad.rlab.be/p/difusionETER que circulé por Telegram. Y un documento md en ETER/proyectodifusion.md para cuando el pad esté listo. 

No cierro el issue así lo seguimos trabajando

**Comment by Danieldaza** [comment]
hice un pdf, ahora lo comparto para que vean que tal.

**Comment by thessaly** [comment]
Cambié bastante el contenido y creo que la cagué en el diseño porque soy malísima =P. Lo hice un poco más "combativo" fíjense si les gusta. Igual hay que darle una vuelta de tuerca más a la 2da página. 

El link para editar sigue siendo el mismo así que metan mano!

**Comment by thessaly** [comment]
Actualicé con la foto que mandó Joaquín, subí la nueva versión del pdf a la carpeta recursos

**Comment by thessaly** [comment]
Contenido ya está definido, falta que lo vea la diseñadora.
