### ISSUE TITLE
Montar servidor en el lab

### ISSUE THREAD

**Issue by vaap07** [rlyehlab/ETER#46]
Se necesita montar un servidor en el lab, par este servidor de contemplar los servicios de:
- Nginx
- postgresql
- flask
- mosquitto

Mosquitto será el broker que servira para gestionar los mensajes de los diferentes tópicos que se requieran. Para poder almacenar la información se necesita la bd de postgresql, puesto que según el servicio que se implemento dentro de la app podría ser interesante trabajar con un campo json o una base de datos relacional.

**Comment by thessaly** [comment]
@vladimirAvilaProsser  este es el issue que habíamos levantado para tener la web, hay algo de data ahí https://github.com/rlyehlab/infra-issues/issues/5

**Comment by vaap07** [comment]
buenisimo!, este basicamente es el que debe proveer los servicios para la aplicación y el broker. Tengo entendido que psyco lo miró

**Comment by thessaly** [comment]
@cuerdo

**Comment by vaap07** [comment]
Se modifica la tecnología. Se requiere levantar una VM  que contemple:
- Mosquitto como broker 
- Nginx
- Nodejs
- React
- Mongo o Postgresql

**Comment by thessaly** [comment]
@HacKanCuBa tenemos que levantar otro issue a infra?

**Comment by thessaly** [comment]
@HacKanCuBa tenemos que levantar otro issue a infra?

**Comment by vaap07** [comment]
Por el momento lo está mirando psyco

**Comment by HacKanCuBa** [comment]
Es otro servidor más o es el mismo?

**Comment by lmaddio** [comment]
Pasemos por favor una estructura nueva hoy, estoy haciendo pruebas para
definir algunas cosas y hasta no tenerlas cerradas no quiero pasarles algo
que puede cambiar tan pronto. Gracias!

**Comment by thessaly** [comment]
This issue was moved to rlyehlab/eter-monitor#4
