### ISSUE TITLE
Materiales del prototipo

### ISSUE THREAD

**Issue by vaap07** [rlyehlab/ETER#52]
Definir los materiales necesarios para implementar un prototipo. Se tiene registrado los siguientes materiales.

- ESP8266 o derivados (NodeMCU)
- DHT22 (Sensor de humedad relativa y temperatura)
- Sharp GP2Y1010AU0F (Sensor de particulas)

a lo anterior le falta contemplar un cooler, batería o forma de alimentación eléctrica

**Comment by thessaly** [comment]
Ok, cierren este porfa https://github.com/rlyehlab/eter/issues/22 porque se duplica

**Comment by thessaly** [comment]
This issue was moved to rlyehlab/eter-monitor#10
